[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tradingagents"
version = "0.1.13-preview"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "akshare",
    "backtrader",
    "baostock",
    "chainlit",
    "chromadb",
    "dashscope",
    "eodhd",
    "feedparser",
    "finnhub-python",
    "google-genai",
    "google-generativeai",
    "langchain-anthropic",
    "langchain-experimental",
    "langchain-google-genai",
    "langchain-openai",
    "langgraph",
    "markdown",
    "openai",
    "pandas",
    "parsel",
    "plotly",
    "praw",
    "psutil",
    "pymongo",
    "pypandoc",
    "python-dotenv",
    "pytdx",
    "pytz",
    "questionary",
    "redis",
    "requests",
    "rich",
    "setuptools",
    "stockstats",
    "streamlit",
    "tqdm",
    "tushare",
    "typing-extensions",
    "yfinance",
]

[project.scripts]
tradingagents = "main:main"

[tool.setuptools.packages.find]
include = ["tradingagents*"]
exclude = ["tests*", "docs*", "scripts*", "data*", "logs*", "reports*", "results*", "eval_results*", "upstream_contribution*"]
